name: Pull Request

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Testing BasisTheoryElements Package
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1.0'

      - name: Testing with IntegrationTester app
        run: exec .github/scripts/integration-test.sh
        env:
          DEV_BT_API_KEY: ${{ secrets.DEV_BT_API_KEY }}
          DEV_PRIVATE_BT_API_KEY: ${{ secrets.DEV_PRIVATE_BT_API_KEY }}
