name: Pull Request

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Testing BasisTheoryElements Package
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: Basis-Theory/basistheory-ios-example
          ref: adds-integration-tester
          token: ${{ secrets.BT_IOS_EXAMPLE_PAT }}
          submodules: true

      - name: Git Sumbodule Update
        run: |
         git pull --recurse-submodules
         git submodule update --remote --recursive

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1.0'

      - name: Testing with IntegrationTester app
        run: exec ./BasisTheoryiOS/.github/scripts/integration-test.sh
        env:
          DEV_BT_API_KEY: ${{ secrets.DEV_BT_API_KEY }}
