name: Pull Request

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Testing BasisTheoryElements Package
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

      - name: Show current version of Xcode
        run: xcodebuild -version

      - name: Testing with IntegrationTester app
        run: exec .github/scripts/integration-test.sh
        env:
          DEV_BT_API_KEY: ${{ secrets.DEV_BT_API_KEY }}
          DEV_PRIVATE_BT_API_KEY: ${{ secrets.DEV_PRIVATE_BT_API_KEY }}

  pod-linting:
    name: Pod Linting
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Pod Linting
        run: pod lib lint --allow-warnings

  dependency-check-test:
    name: Dependency Check Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dependency Check
        run: |
          docker run -v "/home/runner/work/basistheory-ios/basistheory-ios":"/github/workspace" --workdir "/github/workspace" owasp/dependency-check-action:latest --enableExperimental --project "BasisTheoryElements" --failOnCVSS 1 --scan "Package.swift" --out "/github/workspace/reports"

      - name: Upload Test results
        if: success() || failure()
        uses: actions/upload-artifact@master
        with:
           name: Dependency check report
           path: ${{github.workspace}}/reports
