name: Pull Request

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Testing BasisTheory Swift Package
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'

      - name: Testing with IntegrationTester app
        run: exec ./.github/scripts/test_app.sh
        env:
          DEV_BT_API_KEY: ${{ secrets.DEV_BT_API_KEY }}
